### ISSUE TITLE
Cannot fully clone repo

### ISSUE THREAD

**Issue by justcfx2u** [KaixoCode/SpectralRotator#1]
The 'core' folder in the repo links to https://github.com/KaixoCode/SynthCore/tree/14b851d8951fc884c1453425bcb76dc53c2472cc but that link leads to a HTTP 404 error. It appears as though 'SynthCore' is not a public repo, or is restricted in some way which causes cloning of this repo to fail.

**Comment by KaixoCode** [comment]
That is intentional, SynthCore is a private repository. SpectralRotator's source code is public for anyone to look at, but it's not meant to be built by anyone except me.
